@startuml
skinparam linetype ortho
allowmixing

skinparam nodesep 24
skinparam ranksep 10
skinparam padding 4

class user {
~ brain
}

' === BACKEND ===
package "backend" as back_part <<Folder>> {
  class NGinx {}

  package processing {
    package authentification {}
    package way {}
    package notifications {}
    package schedule {}
  }

  package database {
    database postgresql {
    }

    database redis {
    }
  }
}

' === FRONTEND ===
package "frontend" as front_part <<Folder>> {
 package pages {
  class html {}
 }

 package styles {
  class css {}
 }

 package scripts {
  class js {}
 }

 class index_html {}
}

' === DEPENDENCIES ===
user -left--> index_html

index_html --> pages
index_html --> styles
index_html --> scripts


js --> NGinx

' === HIDDEN ===
js -[hidden]right- index_html

' === NOTES ===
@enduml
